# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: database-events
  namespace: postgres
spec:
  selector:
    app: postgres-events
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
