apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: swyw
  name: swyw-deployment-frontend
  labels:
    app: swyw-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swyw-frontend
  template:
    metadata:
      labels:
        app: swyw-frontend
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-init-first: "true"
        vault.hashicorp.com/role: "frontend-role"
        vault.hashicorp.com/agent-inject-secret-frontend.env: "kv/data/frontend"
        vault.hashicorp.com/agent-inject-vault-addr: "http://external-vault.default.svc.cluster.local:8200"
        vault.hashicorp.com/agent-inject-template-frontend.env: |
          {{- with secret "kv/data/frontend" -}}
          export VITE_API_AUTH="{{ .Data.data.VITE_API_AUTH }}"
          export VITE_API_NOTES="{{ .Data.data.VITE_API_NOTES }}"
          {{- end }}
    spec:
      serviceAccountName: frontend-sa
      containers:
        - name: swyw-frontend
          image: camilodevp/swyw-frontend:0.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          command: ["/entrypoint.sh"]
