---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-events-sa
  namespace: swyw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swyw-deployment-backend-events
  namespace: swyw
  labels:
    app: swyw-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swyw-events
  template:
    metadata:
      labels:
        app: swyw-events
      annotations:
        # ðŸ”¹ Habilita la inyecciÃ³n de Vault Agent
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-init-first: "true"

        # ðŸ”¹ Rol de Vault asociado al ServiceAccount
        vault.hashicorp.com/role: "backend-events-role"

        # ðŸ”¹ Secret que serÃ¡ inyectado (ruta exacta en Vault)
        vault.hashicorp.com/agent-inject-secret-config.json: "kv/data/backend-events"

        # ðŸ”¹ DirecciÃ³n del Vault dentro del cluster (servicio "external-vault")
        vault.hashicorp.com/agent-inject-vault-addr: "http://external-vault.default.svc.cluster.local:8200"

        # (Opcional) Define formato del archivo secreto
        vault.hashicorp.com/agent-inject-template-config.json: |
          {{- with secret "kv/data/backend-events" -}}
                     {{- toJSON .Data.data }}
          {{- end }}
    spec:
      serviceAccountName: backend-events-sa
      containers:
        - name: swyw-events
          image: camilodevp/swyw-backend:0.0.5
          ports:
            - containerPort: 3002
          env:
            - name: CONFIG_PATH
              value: "/vault/secrets/config.json"
